# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded "password"
  username: cG9zdGdyZXM=  # base64 encoded "postgres"
  datadog-password: ZGF0YWRvZw==  # base64 encoded "datadog"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  database: userdb
  postgresql.conf: |
    # Basic configuration
    listen_addresses = '*'
    port = 5432
    
    # Enable pg_stat_statements extension
    shared_preload_libraries = 'pg_stat_statements'
    
    # pg_stat_statements configuration
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
    pg_stat_statements.track_utility = off
    pg_stat_statements.save = on
    
    # Logging configuration
    log_statement = 'all'
    log_duration = on
    log_connections = on
    log_disconnections = on
  init-db.sh: |
    #!/bin/bash
    set -e
    
    echo "Starting database initialization..."
    
    # Wait for PostgreSQL to be ready
    until pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 2
    done
    
    echo "PostgreSQL is ready. Creating database and tables..."
    
    # Create userdb database if it doesn't exist
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE userdb'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'userdb');
    \gexec
    EOSQL
    
    echo "Database userdb created or already exists."
    
    # Configure the default postgres database for Datadog DBM
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    
    -- Enable pg_stat_statements extension for Datadog DBM
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
    
    -- Create Datadog monitoring user if not exists
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'datadog') THEN
            CREATE USER datadog WITH PASSWORD 'datadog';
        END IF;
    END
    \$\$;
    
    -- Grant necessary permissions for Datadog DBM
    GRANT pg_monitor TO datadog;
    -- 重要：datadogユーザーがpg_monitorロールから権限を継承できるようにする
    ALTER ROLE datadog INHERIT;
    
    GRANT SELECT ON pg_stat_database TO datadog;
    GRANT SELECT ON pg_stat_database_conflicts TO datadog;
    GRANT SELECT ON pg_stat_bgwriter TO datadog;
    GRANT SELECT ON pg_stat_archiver TO datadog;
    GRANT SELECT ON pg_stat_user_tables TO datadog;
    GRANT SELECT ON pg_stat_user_indexes TO datadog;
    GRANT SELECT ON pg_statio_user_tables TO datadog;
    GRANT SELECT ON pg_statio_user_indexes TO datadog;
    GRANT SELECT ON pg_stat_replication TO datadog;
    GRANT SELECT ON pg_stat_statements TO datadog;
    GRANT SELECT ON pg_stat_activity TO datadog;
    GRANT CONNECT ON DATABASE postgres TO datadog;
    
    -- Create the datadog schema
    CREATE SCHEMA IF NOT EXISTS datadog;
    GRANT USAGE ON SCHEMA datadog TO datadog;
    GRANT CREATE ON SCHEMA datadog TO datadog;
    
    -- Create the explain_statement function for Query Samples
    CREATE OR REPLACE FUNCTION datadog.explain_statement(
       l_query TEXT,
       OUT explain JSON
    )
    RETURNS SETOF JSON AS
    \$\$
    DECLARE
    curs REFCURSOR;
    plan JSON;
    
    BEGIN
       OPEN curs FOR EXECUTE pg_catalog.concat('EXPLAIN (FORMAT JSON) ', l_query);
       FETCH curs INTO plan;
       CLOSE curs;
       RETURN QUERY SELECT plan;
    END;
    \$\$
    LANGUAGE 'plpgsql'
    RETURNS NULL ON NULL INPUT
    SECURITY DEFINER;
    
    EOSQL
    
    echo "Default postgres database configured for Datadog DBM."
    
    # Configure the userdb database for Datadog DBM
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "userdb" <<-EOSQL
    
    -- Enable pg_stat_statements extension for Datadog DBM
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
    
    -- Grant necessary permissions for Datadog DBM on userdb
    GRANT CONNECT ON DATABASE userdb TO datadog;
    
    -- Grant schema permissions first
    GRANT USAGE ON SCHEMA public TO datadog;
    
    ALTER ROLE datadog INHERIT;
    
    -- Create the datadog schema
    CREATE SCHEMA IF NOT EXISTS datadog;
    GRANT USAGE ON SCHEMA datadog TO datadog;
    GRANT CREATE ON SCHEMA datadog TO datadog;
    
    -- Create the explain_statement function for Query Samples
    CREATE OR REPLACE FUNCTION datadog.explain_statement(
       l_query TEXT,
       OUT explain JSON
    )
    RETURNS SETOF JSON AS
    \$\$
    DECLARE
    curs REFCURSOR;
    plan JSON;
    
    BEGIN
       OPEN curs FOR EXECUTE pg_catalog.concat('EXPLAIN (FORMAT JSON) ', l_query);
       FETCH curs INTO plan;
       CLOSE curs;
       RETURN QUERY SELECT plan;
    END;
    \$\$
    LANGUAGE 'plpgsql'
    RETURNS NULL ON NULL INPUT
    SECURITY DEFINER;
    
    -- FIRST: Create application tables
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(255) UNIQUE NOT NULL,
      password VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert test users
    INSERT INTO users (username, password) VALUES 
      ('admin', 'admin123') ON CONFLICT (username) DO NOTHING;
    INSERT INTO users (username, password) VALUES 
      ('user1', 'password1') ON CONFLICT (username) DO NOTHING;
    INSERT INTO users (username, password) VALUES 
      ('test', 'test123') ON CONFLICT (username) DO NOTHING;
    INSERT INTO users (username, password) VALUES 
      ('ctf', 'flag{sql_injection_detected}') ON CONFLICT (username) DO NOTHING;
    
    -- NOW: Create user_activities table (after users table exists)
    CREATE TABLE IF NOT EXISTS user_activities (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      activity_type VARCHAR(50) NOT NULL,
      activity_data JSONB,
      ip_address INET,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- 大量のテストデータを挿入（意図的にインデックスなし）
    INSERT INTO user_activities (user_id, activity_type, activity_data, ip_address, created_at)
    SELECT 
      (random() * 4 + 1)::INTEGER,
      CASE (random() * 4)::INTEGER
        WHEN 0 THEN 'login'
        WHEN 1 THEN 'logout'  
        WHEN 2 THEN 'view_page'
        ELSE 'purchase'
      END,
      ('{"page": "page_' || (random() * 100)::INTEGER || '", "duration": ' || (random() * 1000)::INTEGER || '}')::JSONB,
      ('192.168.1.' || (random() * 255)::INTEGER)::INET,
      NOW() - (random() * interval '30 days')
    FROM generate_series(1, 50000);
    
    -- 遅いクエリを定期的に実行する関数
    CREATE OR REPLACE FUNCTION simulate_slow_queries()
    RETURNS VOID AS \$\$
    DECLARE
        dummy_record RECORD;
    BEGIN
        -- 遅いクエリ1: 日付範囲検索（created_atにインデックスなし）
        FOR dummy_record IN
            SELECT ua.activity_type, ua.created_at, u.username
            FROM user_activities ua
            JOIN users u ON ua.user_id = u.id
            WHERE ua.created_at >= NOW() - INTERVAL '7 days'
            ORDER BY ua.created_at DESC
            LIMIT 10
        LOOP
            -- 何もしない
        END LOOP;
        
        -- 遅いクエリ2: activity_typeでの検索（インデックスなし）
        FOR dummy_record IN
            SELECT COUNT(*) 
            FROM user_activities 
            WHERE activity_type = 'login' 
            AND created_at >= NOW() - INTERVAL '1 day'
        LOOP
            -- 何もしない
        END LOOP;
    END;
    \$\$ LANGUAGE plpgsql;
    
    -- NOW grant permissions on the created tables
    GRANT SELECT ON public.users TO datadog;
    GRANT SELECT ON public.user_activities TO datadog;
    
    -- Verify table creation
    SELECT 'Table users created successfully with ' || COUNT(*) || ' records' FROM users;
    SELECT 'Table user_activities created successfully with ' || COUNT(*) || ' records' FROM user_activities;
    
    EOSQL
    
    echo "Database initialization completed successfully."
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      # annotations:
      #   ad.datadoghq.com/postgres.checks: |
      #     {
      #       "postgres": {
      #         "init_config": {},
      #         "instances": [
      #           {
      #             "dbm": true,
      #             "host": "postgres",
      #             "port": 5432,
      #             "username": "datadog",
      #             "password": "datadog",
      #             "dbname": "userdb",
      #             "disable_generic_tags": false,
      #             "aurora": false,
      #             "query_samples": {
      #               "enabled": true,
      #               "collection_interval": 5
      #             },
      #             "collect_schemas": {
      #               "enabled": true
      #             },
      #             "relations": [
      #               {
      #                 "relation_regex": ".*"
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #     }
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      initContainers:
      - name: init-postgres
        image: postgres:15
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Fixing permissions for PostgreSQL data directory..."
          mkdir -p /var/lib/postgresql/data/pgdata
          chown -R 999:999 /var/lib/postgresql/data
          chmod 700 /var/lib/postgresql/data/pgdata
          echo "Permissions fixed successfully"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
        command: ["docker-entrypoint.sh"]
        args: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "pg_stat_statements.max=10000", "-c", "pg_stat_statements.track=all"]
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-config
          items:
          - key: init-db.sh
            path: init.sh
            mode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tags.datadoghq.com/env: 'ctf'
    tags.datadoghq.com/service: 'postgres'
  annotations:
    ad.datadoghq.com/service.checks: |
      {
        "postgres": {
          "init_config": {},
          "instances": [
            {
              "dbm": true,
              "host": "%%host%%",
              "port": 5432,
              "username": "datadog",
              "password": "datadog",
              "dbname": "userdb",
              "collect_schemas": {
                "enabled": true
              },
              "relations": [
                {
                  "relation_regex": ".*"
                }
              ]
            }
          ]
        }
      }
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: 5432
---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: datadog-postgres-config
#data:
#  postgres.yaml: |
#    init_config:
#    instances:
#    - host: postgres
#      port: 5432
#      username: datadog
#      password: datadog
#      dbname: userdb
#      dbm: true
#      # PostgreSQL 15対応の完全設定
#      collect_function_metrics: true
#      collect_count_metrics: true
#      collect_activity_metrics: true
#      collect_database_size_metrics: true
#      collect_default_database: true
#      # DBM設定
#      query_metrics:
#        enabled: true
#        run_sync: true
#        collection_interval: 10
#      query_activity:
#        enabled: true
#        collection_interval: 10
#      query_samples:
#        enabled: true
#        collection_interval: 10
#      explain_function: datadog.explain_statement
#      explain_parameterized_queries: true
#      settings:
#        enabled: true
#        collection_interval: 600
#      schemas:
#        enabled: true
#        collection_interval: 600
#      resources:
#        enabled: true
#        collection_interval: 600
#      tags:
#        - service:postgres
#        - env:ctf
#        - cluster:swagstore
#        - postgresql_version:15 